### ISSUE TITLE
設計思想の資料化、共有を行う

### ISSUE THREAD

**Issue by 0g3** [ro-2020/ev3#1]
開発にあたり、設計思想を理解する。
コーディング規約のダウンロード、認識、質疑応答

**Comment by 0g3** [comment]
ほげだと思う。

**Comment by roekisou** [comment]
aaa

**Comment by 0g3** [comment]
https://drive.google.com/open?id=1K0_GQ8fGjbs9ToTMGMJLnoImT6FTsYjT
