### ISSUE TITLE
【要件定義】シーソー

### ISSUE THREAD

**Issue by lowfox** [ro-2020/ev3#10]

**Comment by lowfox** [comment]
要件定義↓
https://hackmd.io/DdudUvTdTom8wHofTJIsnA

**Comment by gotou-shinichirou** [comment]
シーソー通過後の前提条件です。
・姿勢は尻尾を降ろした3点倒立状態
・難所通過後、車体が難所から離れすぎていない
・車体がガレージ側に向いている
・難所が車体と接触し移動していない
よろしくお願いします。

**Comment by lowfox** [comment]
![シーソー要求図](https://user-images.githubusercontent.com/40294623/57679908-62095a80-7667-11e9-8c05-1b7f8bf5f2dc.png)

**Comment by lowfox** [comment]
### 松村君から指摘もらったところ
・わからない値（検証が必要な）が多々ある。

分からない値
急減速時のジャイロオフセット値
⇒静的な値…検証が必要
⇒動的な値…加速度（もしくはジャイロ）からPID制御により適切な原則値を生み出す。

シーソー傾き後の静止時間は何秒か。

### 自分のなかで分からないところ

- [ ] シーソー上で倒立振子はどういう動きをするのか。静止してくれるのか。

- [ ] 急減速後、回転数が０になった後の車体の動きはどうなるのか？逆走するのか。

- [ ] 急減速後、ジャイロオフセット値を静止モードに戻すと思うが、その値はどういう値か。

今日（１５日）やること

1. 

まず自分のなかで分からないところを実機を使って検証する。

2.
1.によりわかったのだいたいの定数値を提示する。

3.
ユースケースに移る。

**Comment by lowfox** [comment]
https://drive.google.com/open?id=1-CzP2EjfAKckj5oRL3MdU1wK2_LRXg8D
ジャイロオフセットをいじってみた動画。
予想と違ったから要求定義長引くかも。。
ジャイロオフセットをmain関数でいじって、倒立振子ライブラリに送ってる。
緑色の時がジャイロオフセット値：０
赤色の時がジャイロオフセット値：２０
予想してたのは、２０に設定したらずっと前に進むと思ってた。
でも実際は急加速して少しずつ減速して安定して止まった。
倒立振子のことをもう少し勉強する必要あるかも。。
EV3の倒立振子↓
http://lejos-osek.sourceforge.net/jp/NXTway_GS_C_API.pdf

**Comment by lowfox** [comment]
要件定義【最終】
https://hackmd.io/ltBlfrjvTcGVkplH37wihw

**Comment by lowfox** [comment]
![Screenshot from 2019-05-24 22-55-12](https://user-images.githubusercontent.com/40294623/58332859-20eb2480-7e77-11e9-89d4-67934ecd4f74.png)

**Comment by lowfox** [comment]
変更点
・受け渡されてから倒立解除して尻尾モードで走行する。
・衝突検知後、上りやすい車体角度にする。
