### ISSUE TITLE
旧コースと新コースの比較検証

### ISSUE THREAD

**Issue by Nagisa-Takeuchi** [ro-2020/ev3#109]
旧コースのカーブ角度（大小）と新コースのカーブ角度（大小）が完全に一致しているかどうかを比較検証する。

**Comment by shu3cabe2** [comment]
2016コース
ほとんどのカーブ半径約152mm

2019コース
最小カーブ半径約157mm
小カーブ半径約179mm
大カーブ半径約206mm
最大カーブ半径約255mm

**Comment by shu3cabe2** [comment]
2019コースのカーブは4種類の模様
