### ISSUE TITLE
【要件定義】ルックアップ

### ISSUE THREAD

**Issue by deodorantpower** [ro-2020/ev3#11]

**Comment by gotou-shinichirou** [comment]
ルックアップ終了時の前提条件です。
・姿勢は尻尾を降ろした3点倒立状態
・難所通過後、車体が難所から離れすぎていない
・車体がガレージ側に向いている
・難所が車体と接触し移動していない
頼みます。

**Comment by deodorantpower** [comment]
グレーラインまでのライントレースは白黒の中間を走行する。

**Comment by deodorantpower** [comment]
要件定義
https://hackmd.io/UCkqPJPRSLirUMmaAcrg7w?both
