### ISSUE TITLE
ライントレース [ 要件定義 ]

### ISSUE THREAD

**Issue by shu3cabe2** [ro-2020/ev3#13]

**Comment by shu3cabe2** [comment]
[ライントレース要件定義.docx](https://github.com/ro-2020/ev3/files/3166330/default.docx)

2019/05/10更新

**Comment by Nagisa-Takeuchi** [comment]
[ライントレース要求仕様書ver0.1.docx](https://github.com/ro-2020/ev3/files/3174857/ver0.1.docx)
画像装飾システムにおける要求仕様書に則った形式で上記の「ライントレース要件定義.dock」を書き起こしたもの。
2019/05/14/06:15現在で未完成であるが、本日のROの時間までに共有する必要があるのではないかと考えたためにここに共有する。
一般的に理解されない用語や文章等が内部で用いられている個所があると思われるが、それらの修正、補足等を含めたver1.0の作成が必要である。

**Comment by Nagisa-Takeuchi** [comment]
[ライントレース要求仕様書ver0.11.docx](https://github.com/ro-2020/ev3/files/3176733/ver0.11.docx)
ver0.1で出ていた項目及び若干の追加。

**Comment by eko0427** [comment]
[らいんとれーすだお.docx](https://github.com/ro-2020/ev3/files/3190065/default.docx)
大まかにまとめたやーつ

**Comment by shu3cabe2** [comment]
[ver1.0.docx](https://github.com/ro-2020/ev3/files/3190732/ver1.0.docx)

2019/05/17 授業内未完
タイトルは変えずに進めましょうm(_ _)m

**Comment by eko0427** [comment]
[ver1.1.docx](https://github.com/ro-2020/ev3/files/3200249/ver1.1.docx)

**Comment by Nagisa-Takeuchi** [comment]
[ver1.1.docx](https://github.com/ro-2020/ev3/files/3200369/ver1.1.docx)
とりあえず文章の校正終了。
タイトルは変えずにってことはとりあえずverを上げないで一度ver1.0を完成させるってことでOK?
今回はekoの物に従ってver1.1としたが、文書内のver管理との齟齬も発生しているので、一度認識合わせが必要。
なお、今回UPしたものに関しては文章の校正は行ったが、内容に変更はない。
要求仕様書としては未だ不十分で未完成であることに留意されたし。

**Comment by shu3cabe2** [comment]
[シーソーからの要求]
・角度変化時のライントレース(シーソー傾斜時)
・木材の色をライントレース白として検出させる

**Comment by shu3cabe2** [comment]
[ver1.2.docx](https://github.com/ro-2020/ev3/files/3201343/ver1.2.docx)

2019/05/21 授業内修正版

**Comment by shu3cabe2** [comment]
[ver1.21.docx](https://github.com/ro-2020/ev3/files/3205411/ver1.21.docx)

レビュー後訂正版
