### ISSUE TITLE
キャリブレーションの途中で止まってしまう

### ISSUE THREAD

**Issue by 0g3** [ro-2020/ev3#135]

**Comment by lowfox** [comment]
![image](https://user-images.githubusercontent.com/40294623/64853018-7ed58f00-d655-11e9-88ac-1ccf2bab108a.png)
ログコピーできなかったんでスクショはっと来ました。

挙動しては、
一回目（80度）のきゃりぶれが終わると尻尾が0度になってスタート状態になる

**Comment by 0g3** [comment]
ガレージ側のstandbyが動いている可能性がある。
