### ISSUE TITLE
【ユースケース】シーソー

### ISSUE THREAD

**Issue by lowfox** [ro-2020/ev3#19]

**Comment by lowfox** [comment]
[ETrazicon.zip](https://github.com/ro-2020/ev3/files/3215752/ETrazicon.zip)

**Comment by lowfox** [comment]
![image](https://user-images.githubusercontent.com/40294623/58324574-373ab580-7e62-11e9-8e25-098b3ab72949.png)

**Comment by lowfox** [comment]
![ユースケース図ver2](https://user-images.githubusercontent.com/40294623/58324599-44f03b00-7e62-11e9-9113-65a121b248a9.png)

**Comment by lowfox** [comment]
![ユースケース図ver3](https://user-images.githubusercontent.com/40294623/58331749-c224ab80-7e74-11e9-8e92-1535e1549f62.png)

変更点

- 「昇段する」の尻尾乗り上げを２つに分けた

- 「シーソー上前進、後進」の「シーソー状態に対応する」にミスユースケースをつけて、緩和として速度制御をつなげた

**Comment by lowfox** [comment]
修正
バックで重心をずらしてしっぽで車体をあげる
→バックて重心を前にずらす。

**Comment by lowfox** [comment]
![ユースケース図ver5](https://user-images.githubusercontent.com/40294623/58450752-30a28b80-814b-11e9-96bd-4f9e23e4fdfb.png)

**Comment by lowfox** [comment]
![ユースケース図ver5](https://user-images.githubusercontent.com/40294623/58450801-7e1ef880-814b-11e9-8467-b087163c6657.png)

**Comment by lowfox** [comment]
最終です↑

**Comment by lowfox** [comment]
![ユースケース図ver6](https://user-images.githubusercontent.com/40294623/58452090-094ebd00-8151-11e9-99d7-16f54f00e5a6.png)
追加
・ネガティブアクターの追加

**Comment by saimon0907** [comment]
[ユースケース記述.docx](https://github.com/ro-2020/ev3/files/3225782/default.docx)

**Comment by saimon0907** [comment]
ユースケース記述
1		シーソーをダブル通過する

1-1		シーソーまで移動する
1-1-1		シーソーを検知する
1-1-1-1		灰色を検知
1-1-1-2		振動を検知
1-1-2		停止する
1-1-2-1		倒立解除する
1-1-2-1-1	直進で重心を後ろにする
1-1-2-2		尻尾を下ろす
1-1-3		ライン上を走る
1-1-3-1		ライントレース
1-1-3-2		ライン復帰

1-2		シーソー上を前進、後進する
1-2-1		シーソーの傾きに対応する
1-2-1-1		シーソーの傾きを検知
1-2-1-1-1	ドリフト対策
1-2-1-2		尻尾の角度を更新して、車体の角度を変える
1-2-2-2-1	バックで重心を前にずらす
1-2-1-3		速度制御
1-2-2		ノン・ライントレースする
1-2-2-1		PID制御で左右のモーターの差をなくす

1-3		昇段する
1-3-1		乗り上げる
1-3-1-1		左輪乗り上げる
1-3-1-2		右輪乗り上げる
1-3-1-3		尻尾を乗り上げやすい角度にする
1-3-1-4		乗り上げしないほうのモーターはブレーキする
1-3-2		両輪をそろえる
1-3-2-1		昇段前、車体が斜めに侵入する
1-3-3		尻尾を押し上げて、車体を上げる
1-3-3-1		尻尾を130度にする
1-3-3-2		1-2-2-2-1バックで重心を前にずらす
1-3-4		尻尾を乗り上げる
1-3-4-1		尻尾を80度にする
1-3-4-2		1-2-2ノン・ライントレースする

1-4		後段する
1-4-1		安全着地
1-4-1-1		1-2-2ノン・ライントレースする
1-4-1-2		1-2-1-3	速度制御
1-4-2		後段検知
1-4-2-1		1-1-1-2	振動を検知

2		ガレージの準備をする
2-1		1-2-1-2	尻尾の角度を更新して、車体の角度を変える
2-2		1-1-3-2	ライン復帰

記入漏れ修正
一部　緩和と脅威記述なし

**Comment by lowfox** [comment]
記述の項目のフォーマット（仮）
各ユースケースで必要な項目があると思ったら各自で作って

ユースケース 名｜[UC0]シーソーをダブルで通過する
目的 | 難所シーソーにおいて最高得点で通過する。
アクター | 競技者
事前条件 | ゴール後の灰色前の黒線でライントレース
基本フロー |  
事後条件 |  
例外フロー |

**Comment by lowfox** [comment]
![ユースケース図ver7](https://user-images.githubusercontent.com/40294623/58466581-e33b1400-8174-11e9-995a-3edbf02438c1.png)
## 要件定義の変更による変更
* ライントレースからシーソーに受け渡しは灰色後の黒色検知後、数㎝進んでから。状態はライントレース走行状態。
⇒ユースケースの灰色検知をなくした
* 受け渡し後ライントレース状態から尻尾停止状態にする。
⇒ユースケース「停止」をユースケース「尻尾モードにする」に変更

## 冗長によるユースケースの削除
* 「昇段」、「シーソーまで移動する」の尻尾の角度を動かす系のユースケースを「尻尾の角度を変更する」にまとめた。

**Comment by lowfox** [comment]
メモ
ユースケース記述はユースケース図に順番の要素が加わり、トリガーの項目を加えることで機能を状態として見ることができる。

**Comment by saimon0907** [comment]
ユースケース名　｜[UC4]後段する
目的		｜シーソーから降りる
アクター	｜競技者
事前条件	｜シーソー内でライントレースをやめていること
事後条件	｜走行体が倒れていないこと
基本フロー	｜１	走行体が2回目の前進を始める
		　２	ゆっくりとシーソー端まで向かう
		　３	後段する
脅威		 |１走行体がまっすぐ進まない
３後段時、速すぎると転倒する
緩和		｜１PID制御で左右のモーターの回転数をなくす
３速度制御を行う

ユースケース名　｜安全着地
目的		｜シーソーから降りる際に倒れないように降りること
アクター	｜競技者
事前条件	｜シーソー内でライントレースをやめていること
事後条件	｜走行体が倒れていないこと
基本フロー	｜１	走行体が2回目の前進を始める
		　２	ゆっくりとシーソー端まで向かう
		　３	後段する
脅威		 |１走行体がまっすぐ進まない
３後段時、速すぎると転倒する
緩和		｜１PID制御で左右のモーターの回転数をなくす
３速度制御を行う


ユースケース名　｜後段検知
目的		｜シーソーから降りたことを確認する
アクター	｜競技者
事前条件	｜安全着地に成功していること、振動検知ができていること
事後条件	｜走行体が倒れていないこと
基本フロー	｜１	走行体が2回目の前進を始める
		　２	ゆっくりとシーソー端まで向かう
		　３	後段する
脅威		｜３後段した後にシーソーに引っかかり転倒
緩和		｜３後段した後すぐにライントレースを再開する

中身を少し改善

**Comment by lowfox** [comment]
![ユースケース図ver9](https://user-images.githubusercontent.com/40294623/58684598-b9236500-83b3-11e9-97e4-076f45dfff41.png)

**Comment by saimon0907** [comment]
ユースケース名　｜[UC4]後段する
目的		｜シーソーから降りる
アクター	｜競技者
事前条件	｜倒立走行を行っていること
事後条件	｜走行体がシーソー下で倒立していること
基本フロー	｜１[UC12]ノン・ライントレース
		　２PID制御をしてシーソー端まで走行する
		　３[UC13]安全着地
		　４速度制御をして後段するときの速さを落とす
		　５後段する
		　６[U14]安全停止
		　７後段した際の振動を検知する
		　８[UC12]ノン・ライントレース
		　９シーソーに引っかからないように数センチ進む
脅威		｜１・８まっすぐ進まない
		　３後段時、速すぎると転倒する
		　６後段時シーソーがあがって接触する
緩和		｜２PID制御で左右モーターの回転差をなくす
		　４速度制御を行う
		　９ノンライントレースでシーソーから離れる

**Comment by saimon0907** [comment]
ユースケース名　｜[UC4]後段する
目的		｜シーソーから降りる
アクター	｜競技者
事前条件	｜倒立走行を行っていること
事後条件	｜走行体がシーソー下で倒立していること

基本フロー	｜１[UC12]ノン・ライントレース
		　２PID制御をしてシーソー端まで走行する
		　３[UC13]安全着地
		　４速度制御をして後段するときの速さを落とす
		　５後段する
		　６[U14]安全停止
		　７後段した際の振動を検知する
		　８[UC12]ノン・ライントレース
		　９シーソーに引っかからないように数センチ進む

脅威		｜１・８まっすぐ進まない
		　３後段時、速すぎると転倒する
		　６後段時シーソーがあがって接触する
緩和		｜１・８PID制御で左右モーターの回転差をなくす
		　３・速度制御を行う
		　６ノンライントレースでシーソーから離れる

書き直し[UC4]後段のみ

**Comment by lowfox** [comment]
図、記述のjpeg画像
[ETシーソーダブル攻略.zip](https://github.com/ro-2020/ev3/files/3242649/ET.zip)
astahの元ファイル
[ETシーソーダブル攻略 _astah_pro.zip](https://github.com/ro-2020/ev3/files/3242650/ET._astah_pro.zip)

**Comment by lowfox** [comment]
![ XP X}0](https://user-images.githubusercontent.com/40294623/58743252-fb5aae00-8468-11e9-8da7-f26527d1054f.jpg)
