### ISSUE TITLE
ライントレース分析

### ISSUE THREAD

**Issue by eko0427** [ro-2020/ev3#2]
優秀作品の資料を全部分析し、
共通点の洗い出し、個々のチームの特徴を洗い出し
ミスユースケース（問題点や見逃しやすい箇所）の調査、特定、資料化

**Comment by eko0427** [comment]
ライントレースの書かれている資料のNo.34 48 94 123 168 175 202 241 299

**Comment by eko0427** [comment]
共通点の分析

**Comment by eko0427** [comment]
今現在判明している共通の問題点、可能性
ライン上の黒/白境界と灰色の輝度が同程度であり黒白境界を灰色と誤検知してしまう問題
ルックアップゲート通過姿勢でライントレースをする場合輝度が変化しラインを検知できない問題
ON/OFF制御では無駄な動きが多く滑らかなトレースが実現できない問題
外乱によるカラーセンサで取得した値が変動してしまうためPID制御に影響が出てしまう問題
照明の種類や強度によってカラーセンサが取得する値が変化してしまう問題
一度ラインを見失ってしまうとライン復帰が難しく復帰出来ない可能性が高い問題
シーソー突入後にラインを見失ってしまう問題
分かれ道でラインを誤検知してしまう可能性

**Comment by shu3cabe2** [comment]
シーソー突入後、黒/白の境界、黒/木材の色の茶色の境界へ変化しカラーセンサで誤認してしまう可能性

**Comment by eko0427** [comment]
モーターの個体差があるため、直進出来ない
充電が90%を切ると安定して動かない

**Comment by Nagisa-Takeuchi** [comment]
直進時に速度を上げると、カーブ突入時にラインを飛び越えてしまうのではないか。

**Comment by shu3cabe2** [comment]
https://drive.google.com/file/d/1HAQ57GS6VsQz1vJ0p6E8-H9zrLF5cNA2/view?usp=sharing

遅くなりました。
申し訳ございません。
