### ISSUE TITLE
【ユースケース】ガレージ

### ISSUE THREAD

**Issue by gotou-shinichirou** [ro-2020/ev3#20]

**Comment by gotou-shinichirou** [comment]
![ガレージ・ユースケース図](https://user-images.githubusercontent.com/49894370/58196127-8f5ba580-7d04-11e9-9e91-992bf5381f94.png)

チェック前のガレージユースケース図を作りました。

**Comment by gotou-shinichirou** [comment]
![ユースケース図1](https://user-images.githubusercontent.com/49894370/58308958-de592600-7e3d-11e9-9871-6145f25fc725.png)
チェック済みユースケース図

**Comment by KawakamiShintaro** [comment]
![A220B356-0E2A-4510-913F-73FA4C19A10D](https://user-images.githubusercontent.com/49894428/58451026-a4916380-814c-11e9-8075-bb772dc88125.png)

**Comment by gotou-shinichirou** [comment]
[ガレージ・ユースケース.zip](https://github.com/ro-2020/ev3/files/3235156/default.zip)

.asta形式のユースケース
