### ISSUE TITLE
【ユースケース】ライントレース

### ISSUE THREAD

**Issue by shu3cabe2** [ro-2020/ev3#21]
頑張りませう！

**Comment by eko0427** [comment]
https://drive.google.com/file/d/1M8BzwKdJVA0UQSOp5XB7jmi_T3Xc5aWT/view?usp=sharing

**Comment by shu3cabe2** [comment]
![ユースケース図0](https://user-images.githubusercontent.com/49894424/58312652-b7ebb880-7e46-11e9-80de-503e12a7ca62.jpg)

**Comment by shu3cabe2** [comment]
![ユースケース図0](https://user-images.githubusercontent.com/49894424/58314481-8a087300-7e4a-11e9-8245-d498a017ef78.jpg)
Ver.0.2

**Comment by shu3cabe2** [comment]
![ユースケース図0](https://user-images.githubusercontent.com/49894424/58450711-fcc76600-814a-11e9-968c-abd603a3ee31.jpg)

**Comment by eko0427** [comment]
![ユースケース図0](https://user-images.githubusercontent.com/38448704/58451615-23879b80-814f-11e9-8a97-723633f3c714.jpg)

**Comment by eko0427** [comment]
![ユースケース図0](https://user-images.githubusercontent.com/38448704/58452495-89295700-8152-11e9-8fdf-1ec89e78e7dc.jpg)

**Comment by eko0427** [comment]
![ユースケース図0](https://user-images.githubusercontent.com/38448704/58452568-c0980380-8152-11e9-8d1e-4c20d1d32d76.jpg)

**Comment by eko0427** [comment]
![ユースケース図0](https://user-images.githubusercontent.com/38448704/58452648-15d41500-8153-11e9-9059-a08a634141f3.jpg)

**Comment by eko0427** [comment]
![ユースケース図0](https://user-images.githubusercontent.com/38448704/58453213-300ef280-8155-11e9-98b3-39deb1327a4f.jpg)

**Comment by eko0427** [comment]
![ユースケース図0](https://user-images.githubusercontent.com/38448704/58453345-b9bec000-8155-11e9-805c-72681673ee18.jpg)

**Comment by eko0427** [comment]
https://hackmd.io/UeTzb56rRrqFbI6ASva9nQ

**Comment by shu3cabe2** [comment]
[ver1.22.docx](https://github.com/ro-2020/ev3/files/3240070/ver1.22.docx)

ようけんていぎ
