### ISSUE TITLE
【クラス・シーケンス】シーソー

### ISSUE THREAD

**Issue by lowfox** [ro-2020/ev3#23]

**Comment by lowfox** [comment]
1. 
ユースケースからアクティビティ図を作成
2. 
アクティビティ図⇒オブジェクト図⇒クラス図
3.
アクティビティ図⇒コミュニケーション図⇒シーケンス図
4. 
クラス図⇔シーケンス図

**Comment by saimon0907** [comment]
![①シーソーまで移動する](https://user-images.githubusercontent.com/49894436/59088585-da033180-8942-11e9-9261-4aed47b27e0d.png)

**Comment by saimon0907** [comment]
![①シーソーまで移動する](https://user-images.githubusercontent.com/49894436/59090093-bcd06200-8946-11e9-9abd-e42ce8a0987e.png)

**Comment by saimon0907** [comment]
![①シーソーまで移動する](https://user-images.githubusercontent.com/49894436/59090196-1042b000-8947-11e9-9ba2-1e7b5841225e.png)

**Comment by saimon0907** [comment]
![①シーソーまで移動する](https://user-images.githubusercontent.com/49894436/59093007-dde88100-894d-11e9-8920-58369478f3bb.png)

**Comment by lowfox** [comment]
![シーソーを通過する](https://user-images.githubusercontent.com/40294623/59245882-771cdd80-8c55-11e9-8e3e-062fa2d1582a.png)

**Comment by lowfox** [comment]
![シーソーまで移動するver2](https://user-images.githubusercontent.com/40294623/59254757-c4a44500-8c6b-11e9-869d-a19b58910a5c.png)
尻尾を動かすとこを修正

**Comment by lowfox** [comment]
![1 シーソーまで移動する](https://user-images.githubusercontent.com/40294623/60092431-f8aa5a80-9781-11e9-9e58-5928cdad7468.jpg)
![2 昇段する](https://user-images.githubusercontent.com/40294623/60092437-fba54b00-9781-11e9-8375-84cb76c34b51.jpg)
![3 シーソー上を前進、後進する](https://user-images.githubusercontent.com/40294623/60092442-fd6f0e80-9781-11e9-84bb-481c027d426c.jpg)
![4 降段する](https://user-images.githubusercontent.com/40294623/60092446-ff38d200-9781-11e9-9888-54c1ddd109ca.jpg)
![5 ガレージの準備](https://user-images.githubusercontent.com/40294623/60092451-01029580-9782-11e9-8332-b12046076ee5.jpg)

**Comment by lowfox** [comment]
以下訂正
□で囲んだところはオブジェクト化してる

**Comment by lowfox** [comment]
訂正！
アクティビティ図「シーソーまで移動する」のライントレース走行から尻尾停止する
の最後の「高速でノンライントレース後進を１ｃｍする」するをなくす

**Comment by lowfox** [comment]
シーソーまで移動するのコミュニケーション図
ピンクはオブジェクトの役割
![1．com-シーソーまで移動する](https://user-images.githubusercontent.com/40294623/60324926-0a2d7580-99c1-11e9-864f-1e7a00faad8a.jpg)

**Comment by lowfox** [comment]
![2．com-昇段する](https://user-images.githubusercontent.com/40294623/60327915-1832c480-99c8-11e9-8907-2b0d09ce5081.jpg)

**Comment by lowfox** [comment]
![クラス図ver3](https://user-images.githubusercontent.com/40294623/61099507-8a61d980-a49d-11e9-8675-7bccc7a3e95c.jpg)

**Comment by lowfox** [comment]
![0．seq全体](https://user-images.githubusercontent.com/40294623/61099518-964d9b80-a49d-11e9-87a7-cb4f810925a7.jpg)
![1．seqシーソーまで移動する](https://user-images.githubusercontent.com/40294623/61099519-964d9b80-a49d-11e9-9e95-b2283d2d8ba9.jpg)
![2．seq昇段する](https://user-images.githubusercontent.com/40294623/61099520-964d9b80-a49d-11e9-81d1-5037e9b70ed7.jpg)
![3．seqシーソー上を前後進する](https://user-images.githubusercontent.com/40294623/61099521-964d9b80-a49d-11e9-81d0-7800f3d45d2c.jpg)
![4．seq降段する](https://user-images.githubusercontent.com/40294623/61099524-9c437c80-a49d-11e9-8f81-37a56277d974.jpg)
![5．seqガレージの準備をする](https://user-images.githubusercontent.com/40294623/61099525-9c437c80-a49d-11e9-8ffe-ff4e29c737dc.jpg)

**Comment by lowfox** [comment]
///////////////////////////////走法、メカニズムパッケージの各シーケンス図//////////////////////////////////////
![seqストレートランナー](https://user-images.githubusercontent.com/40294623/61099603-e0368180-a49d-11e9-9810-a104f8b8b203.jpg)
![seqライントレーサー](https://user-images.githubusercontent.com/40294623/61099604-e0cf1800-a49d-11e9-87c2-6c232e850db4.jpg)
![seq安定ブレーカー](https://user-images.githubusercontent.com/40294623/61099606-e0cf1800-a49d-11e9-922d-013c72dc4c4d.jpg)
![seq安定尻尾モーショナー](https://user-images.githubusercontent.com/40294623/61099607-e0cf1800-a49d-11e9-8bfe-8a2f31c44d38.jpg)
![seq角速度検知](https://user-images.githubusercontent.com/40294623/61099608-e0cf1800-a49d-11e9-9c29-44885e203489.jpg)
![seq角度検知](https://user-images.githubusercontent.com/40294623/61099610-e167ae80-a49d-11e9-9a29-4c5952960370.jpg)
![seq姿勢チェンジャー](https://user-images.githubusercontent.com/40294623/61099612-e167ae80-a49d-11e9-9b73-0d2f5e0f0f32.jpg)
![seq車体角度チェンジャー](https://user-images.githubusercontent.com/40294623/61099613-e167ae80-a49d-11e9-943a-2876f0a9357a.jpg)

![seq尻尾](https://user-images.githubusercontent.com/40294623/61099621-e7f62600-a49d-11e9-842e-6efff9a6b055.jpg)
![seq走行距離ランナー](https://user-images.githubusercontent.com/40294623/61099622-e7f62600-a49d-11e9-9351-3156014f0308.jpg)
![seq両輪アライナー](https://user-images.githubusercontent.com/40294623/61099623-e7f62600-a49d-11e9-96e4-d12c7eebc1d2.jpg)
![seqシーソーライダー](https://user-images.githubusercontent.com/40294623/61099631-ed537080-a49d-11e9-84ee-6f50af57e48c.jpg)
![seqシーソーランナー](https://user-images.githubusercontent.com/40294623/61099632-ed537080-a49d-11e9-86e1-47cce7ce99c7.jpg)

**Comment by lowfox** [comment]
[ETシーソーダブル攻略 .asta.zip](https://github.com/ro-2020/ev3/files/3384872/ET.asta.zip)

**Comment by lowfox** [comment]
修正
![4．seq降段する](https://user-images.githubusercontent.com/40294623/61104579-dd458c00-a4b1-11e9-97e8-6e6dc28ee2af.jpg)
![seq走行距離ランナー](https://user-images.githubusercontent.com/40294623/61104580-dd458c00-a4b1-11e9-9811-33dd9b365017.jpg)
![seq両輪アライナー](https://user-images.githubusercontent.com/40294623/61104581-dd458c00-a4b1-11e9-8f9e-880c4ba50f78.jpg)

**Comment by lowfox** [comment]
[ETシーソーダブル攻略 ver1.zip](https://github.com/ro-2020/ev3/files/3385084/ET.ver1.zip)

**Comment by lowfox** [comment]
英語バージョンです。●■などは気にしないでください。
![クラス図ver3eng](https://user-images.githubusercontent.com/40294623/61398120-4db33980-a906-11e9-92b7-83a17297eea0.jpg)
