### ISSUE TITLE
【クラス・シーケンス】ライントレース

### ISSUE THREAD

**Issue by shu3cabe2** [ro-2020/ev3#24]

**Comment by shu3cabe2** [comment]
![シーケンス Bluetoothスタート](https://user-images.githubusercontent.com/49894424/58778601-31856280-860e-11e9-83ea-e64be8fc0056.jpg)

**Comment by shu3cabe2** [comment]
![シーケンス ボタンスタート](https://user-images.githubusercontent.com/49894424/58778622-44983280-860e-11e9-8a95-d7ffbacf9dcb.jpg)

**Comment by shu3cabe2** [comment]
![シーケンス スタート](https://user-images.githubusercontent.com/49894424/58778630-4e219a80-860e-11e9-885b-fb804ca3b8e2.jpg)

↑二つを合体

**Comment by shu3cabe2** [comment]
![シーケンス 初期配置](https://user-images.githubusercontent.com/49894424/58850187-53432000-86c8-11e9-89c8-f25bcc6dcd7b.jpg)

**Comment by shu3cabe2** [comment]
![シーケンス キャリブレーション](https://user-images.githubusercontent.com/49894424/58850198-5f2ee200-86c8-11e9-86e2-fdcd9970360e.jpg)

**Comment by shu3cabe2** [comment]
![シーケンス キャリブレーション](https://user-images.githubusercontent.com/49894424/58852847-16305b00-86d3-11e9-8022-a1f7058b2863.jpg)

**Comment by shu3cabe2** [comment]
![シーケンス キャリブレーション](https://user-images.githubusercontent.com/49894424/59092578-daa0c580-894c-11e9-9638-d96fc524c634.jpg)

**Comment by shu3cabe2** [comment]
![クラス　ライントレース](https://user-images.githubusercontent.com/49894424/59257827-a9d4cf00-8c71-11e9-81d0-65dac5036e24.jpg)

**Comment by shu3cabe2** [comment]
![クラス　ライントレース](https://user-images.githubusercontent.com/49894424/59258117-48613000-8c72-11e9-83b2-ab048918b7cc.jpg)
訂正版

**Comment by shu3cabe2** [comment]
2019/06/25 コミュニケーション図
![コミュニケーション にほんご](https://user-images.githubusercontent.com/49894424/60166914-f5c07000-983c-11e9-8735-c5eaa009fd03.jpg)

**Comment by shu3cabe2** [comment]
![newオブジェクト図](https://user-images.githubusercontent.com/49894424/60195653-6fc11b00-9876-11e9-983c-e8437e13b869.jpg)
19/06/26

**Comment by shu3cabe2** [comment]
![newオブジェクト図SCありver](https://user-images.githubusercontent.com/49894424/60195717-8ebfad00-9876-11e9-84aa-51701adf3cd9.jpg)
12/06/26 ショートカットver.

**Comment by Nagisa-Takeuchi** [comment]
![クラス図ver1 6](https://user-images.githubusercontent.com/41327138/60650348-f54c5880-9e7e-11e9-9449-57bb04ae31fb.png)
レビュー済み。

**Comment by shu3cabe2** [comment]
![シーケンス図-スタート](https://user-images.githubusercontent.com/49894424/60822242-07f8c180-a1e0-11e9-8d02-2c7a55cf5d76.jpg)
![シーケンス図-走行位置更新](https://user-images.githubusercontent.com/49894424/60822266-16df7400-a1e0-11e9-98b6-32be3477be79.jpg)
![シーケンス図-走行情報変更](https://user-images.githubusercontent.com/49894424/60822274-1ba42800-a1e0-11e9-87b2-69ed0d71f296.jpg)
![シーケンス図-(スタートダッシュ)](https://user-images.githubusercontent.com/49894424/60822304-2959ad80-a1e0-11e9-81dd-c9229d71880d.jpg)
![シーケンス図-難所前ゴール改](https://user-images.githubusercontent.com/49894424/60822319-324a7f00-a1e0-11e9-8e73-179b6ab4b9ed.jpg)

**Comment by shu3cabe2** [comment]
お疲れさまでした。
コーディング頑張りましょう！

**Comment by Nagisa-Takeuchi** [comment]
![クラス図ver1 8修正1](https://user-images.githubusercontent.com/41327138/60861665-213c5500-a256-11e9-8490-34d8a3743eb5.png)
最終修正版

**Comment by Nagisa-Takeuchi** [comment]
![クラス図ver1 8修正1](https://user-images.githubusercontent.com/41327138/60870920-b34f5800-a26c-11e9-84fb-acf20e348fe5.png)
TraceがTreaceになっていた問題を修正。

**Comment by Nagisa-Takeuchi** [comment]
![クラス図ver1 8 2](https://user-images.githubusercontent.com/41327138/61063929-cbc19d00-a43b-11e9-8066-56a0f76652ef.png)
エラーチェック用にenum MapStateの最後にStateEndを追加しました。

**Comment by Nagisa-Takeuchi** [comment]
![クラス図ver1 9](https://user-images.githubusercontent.com/41327138/61113959-50f39300-a4ca-11e9-8b1a-104efe6a8f6c.png)
マップステータスを管理するための構造体を追加。

**Comment by Nagisa-Takeuchi** [comment]
![クラス図ver1 9 2](https://user-images.githubusercontent.com/41327138/61166747-e2681100-a56d-11e9-84b5-5352266f6b34.png)
MapStateControlのメンバ変数に左右両コースの走行手順を保存した構造体DriveStateを追加。

**Comment by Nagisa-Takeuchi** [comment]
![クラス図ver1 9 3](https://user-images.githubusercontent.com/41327138/61180095-d0f53680-a64b-11e9-9144-7cc4190e9839.png)
MapStateControlの不要だったメンバ変数m_mapStateを削除しました。
