### ISSUE TITLE
【クラス・シーケンス】ルックアップ

### ISSUE THREAD

**Issue by deodorantpower** [ro-2020/ev3#25]

**Comment by deodorantpower** [comment]
![クラス図0](https://user-images.githubusercontent.com/41692106/58860662-93fe6180-86e7-11e9-9483-34ca2cb636f9.jpg)

**Comment by deodorantpower** [comment]
パッケージ名、クラス名、関数名の見直しを行う。

**Comment by deodorantpower** [comment]
![クラス図0](https://user-images.githubusercontent.com/41692106/59498741-f8cc6f80-8ed0-11e9-8c2f-5044d5555f40.jpg)

**Comment by deodorantpower** [comment]
MasterControlの仕事を分けたクラス図
![ルックアップゲート攻略クラス図](https://user-images.githubusercontent.com/41692106/59971476-aa496000-95b7-11e9-9f5e-475e9b75a801.jpg)

**Comment by deodorantpower** [comment]
先生のレビューを受けた結果
黄色の部分が指摘部分
![ルックアップゲートクラス図](https://user-images.githubusercontent.com/41692106/60195377-ee698880-9875-11e9-994f-864603bac100.jpg)

**Comment by deodorantpower** [comment]
ゲート攻略の「ダブル」から「トリプル」への仕様変更に伴い半回転後のラインの見失いのリスク軽減のため、半回転後三点走行状態のまま80°まで態勢を戻しトレースしながら、超音波センサを使用し停止、再び車体を傾けゲートを通過を繰り返すことにする。

**Comment by deodorantpower** [comment]
![クラス図1](https://user-images.githubusercontent.com/41692106/60404482-6e7c4f00-9be4-11e9-802c-7b68c3424ca5.jpg)

**Comment by deodorantpower** [comment]
レビュー訂正内容
・Motor_Controlのprivate変数をint -> floatに変更
・Phase1の尻尾を下ろした後、倒立解除する
・Mainクラスの追加
・Tail_Control内での処理でのloopの不要と角度を指示してSpeedで調整する
・Emergency_Controlの処理の動きの修正
・Phase毎のメソッド戻り値の修正　

7/4までに修正し、再レビューしてもらいやすくする。

**Comment by deodorantpower** [comment]
尻尾を下ろすときゆっくり走りながらのパターンを考えてみる

**Comment by deodorantpower** [comment]
走行体の角度を尻尾走行のまま、62°～80°に戻すとき、安定させたいためバック走行をしながらするシーケンスを書く

**Comment by deodorantpower** [comment]
確認項目
・Motor_ControlのCompare_Valの引数が必要か
・csPhase2ゲート通過チェックの再確認
・半回転の部分を80°に戻してからにするかどうか

**Comment by deodorantpower** [comment]
確認事項追加
・Phase3ライン検知のLine_CheckメソッドとPhase3ライン復帰のStart_Colorの違いが判らない

**Comment by voltace12** [comment]
最新バージョン
![クラス図0](https://user-images.githubusercontent.com/49894417/60714860-d02b1900-9f56-11e9-802b-3dc16710ecff.jpg)
