### ISSUE TITLE
ミドルウェア設計

### ISSUE THREAD

**Issue by 0g3** [ro-2020/ev3#26]
https://paper.dropbox.com/doc/MW--AeZzjEC8ogGch0MVwGPkleFOAg-J6DNDYOqykl3JKAYE7Ip8

**Comment by eko0427** [comment]
![____________0](https://user-images.githubusercontent.com/38448704/59092763-497e1e80-894d-11e9-8375-613424b6ff3a.png)
クラス図

**Comment by eko0427** [comment]
rotate() はライン+走行距離を確認して180度回転を行う
