### ISSUE TITLE
フルサイズコースを用意する

### ISSUE THREAD

**Issue by Nagisa-Takeuchi** [ro-2020/ev3#36]
様々な検証、実証試験用にフルサイズのコースを用意する必要があるのではないか。
作成するならば、作成方法、材料、担当者、予算を協議しなければならない。

**Comment by Nagisa-Takeuchi** [comment]
各部分(直線、右大カーブ、右小カーブ、左大カーブ、左小カーブ)毎に1/1スケールでコースを作成する。
担当者　佐々木

**Comment by yumaa6122** [comment]
ロール紙　4960円
