### ISSUE TITLE
ガレージのコードのデバッグ

### ISSUE THREAD

**Issue by gotou-shinichirou** [ro-2020/ev3#40]

**Comment by gotou-shinichirou** [comment]
テストコード
[https://qiita.com/ta_ta_ta_miya/items/427de7237cf109c9c39b](url)

**Comment by gotou-shinichirou** [comment]
コーディング役割分担
藤岡君・・・provision_range_calculation 青ライン終端からガレージインまでの総距離を青ラインの総距離から比率で既定距離を求める

後藤・・・blue_line_total_range_calculation 青ラインの総距離を求める

川上君・・・check_up_to_garage_in 青ライン終端からガレージまでの既定距離を走行したかをチェック

**Comment by voltace12** [comment]
解決しました
