### ISSUE TITLE
ドッカーのビルドに失敗する

### ISSUE THREAD

**Issue by eko0427** [ro-2020/ev3#45]
ドッカーを使ってビルドを行った時にコードが初期の状態に戻されビルドされてちゃんと出来ないバグ
なんで？

// ビルド前のコード
		if ((traceColor.blue.b * 0.7) < rgb.b && (traceColor.blue.r + traceColor.blue.g) * 0.8 < (rgb.r + rgb.g))
		{
			return ReadColor::BLUE;
		}

// ビルド後のコード
		if ((rgb.r + rgb.g) < rgb.b)
		{
			return ReadColor::BLUE;
		}

**Comment by 0g3** [comment]
対応します🙇‍♂️

**Comment by eko0427** [comment]
$ docker pull ubuntu:18.04
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by eko0427** [comment]
https://satoyashiki.hatenablog.com/entry/2017/04/01/175604

**Comment by 0g3** [comment]
## コードが消える問題解決方法
- runする前にするビルドする（初回ビルドは時間かかります）
```
docker build . -t ev3dev:v1
```
- run　（⚠️：未検証）
