### ISSUE TITLE
車庫入れ分析

### ISSUE THREAD

**Issue by gotou-shinichirou** [ro-2020/ev3#5]

**Comment by KawakamiShintaro** [comment]
優秀作品の資料を3人で調査

**Comment by gotou-shinichirou** [comment]
[ガレージ込み.pptx](https://github.com/ro-2020/ev3/files/3106886/default.pptx)
一応、ガレージまでの設計してる

**Comment by gotou-shinichirou** [comment]
[ガレージ.pdf](https://github.com/ro-2020/ev3/files/3107007/default.pdf)
みっけた

**Comment by Ftomoya** [comment]
file:///C:/Users/ohs75006/Documents/ETロボコン/chiku_model_all/chiku_model_all/9/289/289_1_JK4dT4y5193.pdf

**Comment by KawakamiShintaro** [comment]
[046_1_N22XmoY8296.pdf](https://github.com/ro-2020/ev3/files/3111854/046_1_N22XmoY8296.pdf)

**Comment by gotou-shinichirou** [comment]
[ガレージ一覧.zip](https://github.com/ro-2020/ev3/files/3119719/default.zip)

**Comment by gotou-shinichirou** [comment]
ガレージ一覧.zipは2016～2018までの全てのプライマリクラスからガレージ分析を選択したチームのUML一覧である。

**Comment by gotou-shinichirou** [comment]
https://drive.google.com/file/d/1LtNn0WyOuMXRnUmVSRcVxhZRUplhabM4/view?usp=drivesdk

**Comment by gotou-shinichirou** [comment]
資料
https://drive.google.com/file/d/1LtNn0WyOuMXRnUmVSRcVxhZRUplhabM4/view?usp=drivesdk
