### ISSUE TITLE
【チューニング】ルックアップ

### ISSUE THREAD

**Issue by deodorantpower** [ro-2020/ev3#91]

**Comment by deodorantpower** [comment]
Drive(10)
Drive::LineTrace::SetPID({ 0.3f, 0.0f, 0.2f })
にして1分06秒

**Comment by 0g3** [comment]
## TODO
- [ ] １分以内のクリア

- [ ] 安定化（※１）

## memo
（※１）５０回中４５回以上の成功率を達成すること。

**Comment by deodorantpower** [comment]
超音波センサの検知距離を短縮することで調整

**Comment by deodorantpower** [comment]
キャリブレーションの値によって安定化が変化する

**Comment by deodorantpower** [comment]
５０分の４１で８２％
原因：
・バックしながら走行体の体制を戻すとき、モーターが上がりきらずバックのまま後退　１件
・他、超音波センサの反応しない
